import Head from 'next/head'
import Image from 'next/image'
import { useTheme } from "next-themes";

export default function Home() {
  const { theme, setTheme } = useTheme();

  console.log(typeof theme)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => setTheme("light")}>Light Mode</button>
        <button onClick={() => setTheme("dark")}>Dark Mode</button>
      </main>
    </>
  );
}
