name: Update Website Screenshot

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright
        run: |
          npx playwright install --with-deps chromium

      - name: Build website
        run: pnpm build

      - name: Start server and take screenshot
        run: |
          # Start the development server in background
          pnpm dev &
          SERVER_PID=$!

          # Wait for server to be ready
          timeout=30
          while [ $timeout -gt 0 ]; do
            if curl -f http://localhost:3000 > /dev/null 2>&1; then
              echo "Server is ready"
              break
            fi
            echo "Waiting for server to start... ($timeout seconds left)"
            sleep 1
            timeout=$((timeout - 1))
          done

          if [ $timeout -eq 0 ]; then
            echo "Server failed to start"
            exit 1
          fi

          # Take screenshot
          npx playwright screenshot \
            --viewport-size=1280,720 \
            --full-page \
            --wait-for-timeout=3000 \
            http://localhost:3000 \
            static/images/website-screenshot.png

          # Clean up
          kill $SERVER_PID

      - name: Commit screenshot
        run: |
          # Disable git hooks to prevent pre-commit from running in CI
          git config core.hooksPath /dev/null
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add static/images/website-screenshot.png
          git diff --staged --quiet || git commit -m "Update website screenshot [skip ci]"
          git push
